<?php
declare(strict_types=1);

// Gemini SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

GeminiUtility::setRegistrar(function (GeminiUtility $u): void {
    $u->clean = [GeminiClean::class, 'call'];
    $u->done = [GeminiDone::class, 'call'];
    $u->make_error = [GeminiMakeError::class, 'call'];
    $u->feature_add = [GeminiFeatureAdd::class, 'call'];
    $u->feature_hook = [GeminiFeatureHook::class, 'call'];
    $u->feature_init = [GeminiFeatureInit::class, 'call'];
    $u->fetcher = [GeminiFetcher::class, 'call'];
    $u->make_fetch_def = [GeminiMakeFetchDef::class, 'call'];
    $u->make_context = [GeminiMakeContext::class, 'call'];
    $u->make_options = [GeminiMakeOptions::class, 'call'];
    $u->make_request = [GeminiMakeRequest::class, 'call'];
    $u->make_response = [GeminiMakeResponse::class, 'call'];
    $u->make_result = [GeminiMakeResult::class, 'call'];
    $u->make_point = [GeminiMakePoint::class, 'call'];
    $u->make_spec = [GeminiMakeSpec::class, 'call'];
    $u->make_url = [GeminiMakeUrl::class, 'call'];
    $u->param = [GeminiParam::class, 'call'];
    $u->prepare_auth = [GeminiPrepareAuth::class, 'call'];
    $u->prepare_body = [GeminiPrepareBody::class, 'call'];
    $u->prepare_headers = [GeminiPrepareHeaders::class, 'call'];
    $u->prepare_method = [GeminiPrepareMethod::class, 'call'];
    $u->prepare_params = [GeminiPrepareParams::class, 'call'];
    $u->prepare_path = [GeminiPreparePath::class, 'call'];
    $u->prepare_query = [GeminiPrepareQuery::class, 'call'];
    $u->graphql_body = [GeminiGraphql::class, 'body'];
    $u->graphql_errors = [GeminiGraphql::class, 'errors'];
    $u->result_basic = [GeminiResultBasic::class, 'call'];
    $u->result_body = [GeminiResultBody::class, 'call'];
    $u->result_headers = [GeminiResultHeaders::class, 'call'];
    $u->transform_request = [GeminiTransformRequest::class, 'call'];
    $u->transform_response = [GeminiTransformResponse::class, 'call'];
});
